<?php

namespace HnhDigital\LinodeApi;

/*
 * This file is part of the PHP Linode API.
 *
 * (c) H&H|Digital <hello@hnh.digital>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use HnhDigital\LinodeApi\Foundation\Base;

/**
 * This is the Images class.
 *
 * This file is automatically generated.
 *
 * @link https://developers.linode.com/api/v4#tag/Images
 *
 * @author Rocco Howard <rocco@hnh.digital>
 */
class Images extends Base
{
    /**
     * Endpoint.
     *
     * @var string
     */
    protected $endpoint = 'images';
    /**
     * Constructor.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Returns a paginated list of Images.
     * 
     * - Calling this endpoint without authentication returns all public Images.
     * - Authentication is required to return a combined paginated list of all public and
     *   your private Images.
     *
     * @link https://developers.linode.com/api/v4#operation/getImages
     *
     * @return array
     */
    public function get()
    {
        return $this->apiCall('get', '');
    }

    /**
     * Creates a private gold-master Image from a Linode Disk. There is no additional charge to store Images for Linode users.
     * Images are limited to three per Account.
     *
     * @link https://developers.linode.com/api/v4#operation/createImage
     *
     * @return mixed
     */
    public function create()
    {
        return $this->apiCall('post', '');
    }
}
