<?php

namespace HnhDigital\LinodeApi;

/*
 * This file is part of the PHP Linode API.
 *
 * (c) H&H|Digital <hello@hnh.digital>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use HnhDigital\LinodeApi\Foundation\Base;

/**
 * This is the NodeBalancers class.
 *
 * This file is automatically generated.
 *
 * @link https://developers.linode.com/v4/reference/endpoints/nodebalancers
 *
 * @author Rocco Howard <rocco@hnh.digital>
 */
class NodeBalancers extends Base
{
    /**
     * Endpoint.
     *
     * @var string
     */
    protected $endpoint = 'nodebalancers';
    /**
     * Type.
     *
     * @var array
     */
    public $type = [
        'master' => 'Master',
        'slave'  => 'Slave',
    ];

    /**
     * Status.
     *
     * @var array
     */
    public $status = [
        'disabled'  => 'Disabled',
        'active'    => 'Active',
        'edit_mode' => 'Edit mode',
    ];

    /**
     * Constructor.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Returns a list of NodeBalancers.
     *
     * @link https://developers.linode.com/v4/reference/endpoints/nodebalancers#GET
     *
     * @return array
     */
    public function search()
    {
        return $this->apiSearch($this->endpoint);
    }

    /**
     * Creates a new NodeBalancer.
     *
     * @param json  $region   A region ID to provision this NodeBalancer in.
     * @param array $optional
     *                        - [label] (string) The label to assign this NodeBalancer. Defaults to "nodebalancer" followed by its ID.
     *                        - [client_conn_throttle] (string) To help mitigate abuse, throttle connections per second, per client. 0 to disable, max of 20.
     *
     * @link https://developers.linode.com/v4/reference/endpoints/nodebalancers#POST
     *
     * @return bool
     */
    public function create($region, $optional = [])
    {
        return $this->call('post', '', array_merge([
            'region' => $region,
        ], $optional));
    }
}
