<?php

namespace HnhDigital\LinodeApi;

/*
 * This file is part of the PHP Linode API.
 *
 * (c) H&H|Digital <hello@hnh.digital>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use HnhDigital\LinodeApi\Api;

/**
 * This is the StackScript class.
 *
 * This file is automatically generated.
 *
 * @link https://developers.linode.com/v4/reference/endpoints/linode/stackscripts
 * @author Rocco Howard <rocco@hnh.digital>
 */
class StackScript extends Api
{
    /**
     * Endpoint.
     *
     * @var string
     */
    protected $endpoint = 'linode/stackscripts//%s';

    /**
     * Endpoint placeholders.
     *
     * @var array
     */
    protected $endpoint_placeholders = [];

    /**
     * stackscript_id.
     *
     * @var integer
     */
    protected $stackscript_id;

    /**
     * Constructor.
     *
     * @return void
     */
    public function __construct($stackscript_id, $load = true)
    {
        $this->stackscript_id = $stackscript_id;
        $this->endpoint_placeholders = [$stackscript_id];
    }

    /**
     * Returns information about this StackScript.
     *
     * @link https://developers.linode.com/v4/reference/endpoints/linode/stackscripts/$id#GET
     *
     * @return array
     */
    public function get()
    {
        return $this->call('get', '');
    }

    /**
     * Edits this StackScript.
     *
     * @param array $optional 
     *      - [label] (string) 
     * 
     * @link https://developers.linode.com/v4/reference/endpoints/linode/stackscripts/$id#PUT
     *
     * @return void
     */
    public function update($optional)
    {
        return $this->call('put', "", $optional);
    }

    /**
     * Deletes this StackScript. This action cannot be undone.
     *
     * @link https://developers.linode.com/v4/reference/endpoints/linode/stackscripts/$id#DELETE
     *
     * @return void
     */
    public function delete()
    {
        return $this->call('delete', "");
    }

}
