<?php

namespace HnhDigital\LinodeApi\Account\Payments;

/*
 * This file is part of the PHP Linode API.
 *
 * (c) H&H|Digital <hello@hnh.digital>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use HnhDigital\LinodeApi\Foundation\Base;

/**
 * This is the Paypal class.
 *
 * This file is automatically generated.
 *
 * @link https://developers.linode.com/api/v4#tag/Account-Payments-Paypal
 *
 * @author Rocco Howard <rocco@hnh.digital>
 */
class Paypal extends Base
{
    /**
     * Endpoint.
     *
     * @var string
     */
    protected $endpoint = 'account/payments/paypal';
    /**
     * Constructor.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * This begins the process of submitting a Payment via PayPal. After calling this endpoint, you must take the resulting
     * `payment_id` along with the `payer_id` from your PayPal account and [POST
     * /account/payments/paypal-execute](/#operation/executePayPalPayment) to complete the Payment.
     *
     * @link https://developers.linode.com/api/v4#operation/createPayPalPayment
     *
     * @return mixed
     */
    public function createPayPalPayment()
    {
        return $this->apiCall('post', '');
    }
}
