<?php

namespace HnhDigital\LinodeApi\Managed;

/*
 * This file is part of the PHP Linode API.
 *
 * (c) H&H|Digital <hello@hnh.digital>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use HnhDigital\LinodeApi\Foundation\Base;

/**
 * This is the Issue class.
 *
 * This file is automatically generated.
 *
 * @link https://developers.linode.com/api/v4#tag/Managed-Issues
 *
 * @author Rocco Howard <rocco@hnh.digital>
 */
class Issue extends Base
{
    /**
     * Endpoint.
     *
     * @var string
     */
    protected $endpoint = 'managed/issues/%s';
    /**
     * Issue Id.
     *
     * @var 
     */
    protected $issue_id;

    /**
     * Constructor.
     *
     * @return void
     */
    public function __construct($issue_id)
    {
        $this->issue_id = $issue_id;
        parent::__construct($issue_id);
    }

    /**
     * Returns a single Issue that is impacting or did impact one of your Managed Services.
     *
     * @link https://developers.linode.com/api/v4#operation/getManagedIssue
     *
     * @return array
     */
    public function get()
    {
        return $this->apiCall('get', '');
    }
}
