<?php

namespace HnhDigital\LinodeApi\Managed;

/*
 * This file is part of the PHP Linode API.
 *
 * (c) H&H|Digital <hello@hnh.digital>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use HnhDigital\LinodeApi\Foundation\Base;

/**
 * This is the Services class.
 *
 * This file is automatically generated.
 *
 * @link https://developers.linode.com/api/v4#tag/Managed-Services
 *
 * @author Rocco Howard <rocco@hnh.digital>
 */
class Services extends Base
{
    /**
     * Endpoint.
     *
     * @var string
     */
    protected $endpoint = 'managed/services';

    /**
     * Constructor.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
* Returns a paginated list of Managed Services on your Account. These are the services Linode Managed is monitoring and
     * will report and attempt to resolve issues with.
     *
     * @link https://developers.linode.com/api/v4#operation/getManagedServices
     *
     * @return array
     */
    public function get()
    {
        return $this->apiCall('get', '');
    }

    /**
* Creates a Managed Service. Linode Managed will being monitoring this service and reporting and attempting to resolve any
     * Issues.
     *
     * @link https://developers.linode.com/api/v4#operation/createManagedService
     *
     * @return mixed
     */
    public function create()
    {
        return $this->apiCall('post', '');
    }
}
