<?php

namespace HnhDigital\LinodeApi\Linode;

/*
 * This file is part of the PHP Linode API.
 *
 * (c) H&H|Digital <hello@hnh.digital>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use HnhDigital\LinodeApi\Foundation\Base;

/**
 * This is the Kernel class.
 *
 * This file is automatically generated.
 *
 * @link https://developers.linode.com/api/v4#tag/Linode-Kernels
 *
 * @author Rocco Howard <rocco@hnh.digital>
 */
class Kernel extends Base
{
    /**
     * Endpoint.
     *
     * @var string
     */
    protected $endpoint = 'linode/kernels/%s';
    /**
     * Kernel Id.
     *
     * @var 
     */
    protected $kernel_id;

    /**
     * Constructor.
     *
     * @return void
     */
    public function __construct($kernel_id)
    {
        $this->kernel_id = $kernel_id;
        parent::__construct($kernel_id);
    }

    /**
     * Returns information about a single Kernel.
     *
     * @link https://developers.linode.com/api/v4#operation/getKernel
     *
     * @return array
     */
    public function get()
    {
        return $this->apiCall('get', '');
    }
}
