<?php

namespace HnhDigital\LinodeApi\Longview;

/*
 * This file is part of the PHP Linode API.
 *
 * (c) H&H|Digital <hello@hnh.digital>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use HnhDigital\LinodeApi\Foundation\Base;

/**
 * This is the Clients class.
 *
 * This file is automatically generated.
 *
 * @link https://developers.linode.com/v4/reference/endpoints/longview/clients
 *
 * @author Rocco Howard <rocco@hnh.digital>
 */
class Clients extends Base
{
    /**
     * Endpoint.
     *
     * @var string
     */
    protected $endpoint = 'longview/clients';
    /**
     * Constructor.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Returns a list of regions.
     *
     * @link https://developers.linode.com/v4/reference/endpoints/regions#GET
     *
     * @return array
     */
    public function search()
    {
        return $this->apiSearch($this->endpoint, ['class' => 'Client', 'parameters' => ['id']]);
    }

    /**
     * Creates a new Longview client.
     *
     * @param array $optional
     *                        - [label] (string) The label to assign this Longview client.
     *
     * @link https://developers.linode.com/v4/reference/endpoints/longview/clients#POST
     *
     * @return bool
     */
    public function create($optional = [])
    {
        return $this->apiCall('post', '', ['json' => array_merge([
        ], $optional)]);
    }
}
