<?php

namespace HnhDigital\LinodeApi\Longview;

/*
 * This file is part of the PHP Linode API.
 *
 * (c) H&H|Digital <hello@hnh.digital>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use HnhDigital\LinodeApi\Foundation\Base;

/**
 * This is the Subscriptions class.
 *
 * This file is automatically generated.
 *
 * @link https://developers.linode.com/api/v4#tag/Longview-Subscriptions
 *
 * @author Rocco Howard <rocco@hnh.digital>
 */
class Subscriptions extends Base
{
    /**
     * Endpoint.
     *
     * @var string
     */
    protected $endpoint = 'longview/subscriptions';

    /**
     * Constructor.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
* Returns a paginated list of available Longview Subscriptions. This is a public endpoint and requires no authentication.
     *
     * @link https://developers.linode.com/api/v4#operation/getLongviewSubscriptions
     *
     * @return array
     */
    public function get()
    {
        return $this->apiCall('get', '');
    }
}
