<?php

namespace HnhDigital\LinodeApi\Longview;

/*
 * This file is part of the PHP Linode API.
 *
 * (c) H&H|Digital <hello@hnh.digital>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use HnhDigital\LinodeApi\Foundation\Base;

/**
 * This is the Subscription class.
 *
 * This file is automatically generated.
 *
 * @link https://developers.linode.com/v4/reference/endpoints/longview/subscriptions/$id
 *
 * @author Rocco Howard <rocco@hnh.digital>
 */
class Subscription extends Base
{
    /**
     * Endpoint.
     *
     * @var string
     */
    protected $endpoint = 'longview/subscriptions/%s';
    /**
     * Client Id.
     *
     * @var int
     */
    protected $client_id;
    /**
     * Constructor.
     *
     * @return void
     */
    public function __construct($client_id)
    {
        $this->client_id = $client_id;
        parent::__construct($client_id);
    }

    /**
     * Returns information about this Longview client.
     *
     * @link https://developers.linode.com/v4/reference/endpoints/longview/subscriptions/$id#GET
     *
     * @return array
     */
    public function get()
    {
        return $this->apiCall('get', '');
    }
}
