<?php

namespace HnhDigital\LinodeApi\Account\Payment\Paypal;

/*
 * This file is part of the PHP Linode API.
 *
 * (c) H&H|Digital <hello@hnh.digital>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use HnhDigital\LinodeApi\Foundation\Base;

/**
 * This is the Execute class.
 *
 * This file is automatically generated.
 *
 * @link https://developers.linode.com/api/v4#tag/Account-Payment-Paypal-Execute
 *
 * @author Rocco Howard <rocco@hnh.digital>
 */
class Execute extends Base
{
    /**
     * Endpoint.
     *
     * @var string
     */
    protected $endpoint = 'account/payment/paypal/execute';
    /**
     * Constructor.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Given a PaymentID and PayerID - as generated by PayPal during the transaction authorization process - this endpoint executes the Payment to capture the funds and credit your Linode Account.

     *
     * @link https://developers.linode.com/api/v4#operation/executePayPalPayment
     *
     * @return mixed
     */
    public function executePayPalPayment()
    {
        return $this->apiCall('post', '');
    }
}
