<?php

namespace HnhDigital\LinodeApi\Profile;

/*
 * This file is part of the PHP Linode API.
 *
 * (c) H&H|Digital <hello@hnh.digital>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use HnhDigital\LinodeApi\Foundation\Base;

/**
 * This is the TfaEnableConfirm class.
 *
 * This file is automatically generated.
 *
 * @link https://developers.linode.com/api/v4#tag/Profile-TfaEnableConfirm
 *
 * @author Rocco Howard <rocco@hnh.digital>
 */
class TfaEnableConfirm extends Base
{
    /**
     * Endpoint.
     *
     * @var string
     */
    protected $endpoint = 'profile/tfa-enable-confirm';

    /**
     * Constructor.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Confirms that you can successfully generate Two Factor codes and enables TFA on your Account. Once this is complete,
     * login attempts from untrusted computers will be required to provide a Two Factor code before they are successful.
     *
     * @link https://developers.linode.com/api/v4#operation/tfaConfirm
     *
     * @return mixed
     */
    public function tfaConfirm()
    {
        return $this->apiCall('post', '');
    }
}
