<?php

namespace HnhDigital\LinodeApi\Networking\Ipv4;

/*
 * This file is part of the PHP Linode API.
 *
 * (c) H&H|Digital <hello@hnh.digital>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use HnhDigital\LinodeApi\Foundation\Base;

/**
 * This is the Assign class.
 *
 * This file is automatically generated.
 *
 * @link https://developers.linode.com/api/v4#tag/Networking-Ipv4-Assign
 *
 * @author Rocco Howard <rocco@hnh.digital>
 */
class Assign extends Base
{
    /**
     * Endpoint.
     *
     * @var string
     */
    protected $endpoint = 'networking/ipv4/assign';
    /**
     * Constructor.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Assign multiple IPs to multiple Linodes in one Region. This allows swapping, shuffling, or otherwise reorganizing IPv4
     * Addresses to your Linodes.  When the assignment is finished, all Linodes must end up with at least one public IPv4 and
     * no more than one private IPv4.
     *
     * @link https://developers.linode.com/api/v4#operation/assignIPs
     *
     * @return mixed
     */
    public function assignIPs()
    {
        return $this->apiCall('post', '');
    }
}
