<?php

namespace HnhDigital\LinodeApi\Networking\Ipv4;

/*
 * This file is part of the PHP Linode API.
 *
 * (c) H&H|Digital <hello@hnh.digital>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use HnhDigital\LinodeApi\Foundation\Base;

/**
 * This is the Share class.
 *
 * This file is automatically generated.
 *
 * @link https://developers.linode.com/api/v4#tag/Networking-Ipv4-Share
 *
 * @author Rocco Howard <rocco@hnh.digital>
 */
class Share extends Base
{
    /**
     * Endpoint.
     *
     * @var string
     */
    protected $endpoint = 'networking/ipv4/share';

    /**
     * Constructor.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Configure shared IPs.  A shared IP may be brought up on a Linode other than the one it lists in its response.  This can
     * be used to allow one Linode to begin serving requests should another become unresponsive.
     *
     * @link https://developers.linode.com/api/v4#operation/shareIPs
     *
     * @return mixed
     */
    public function shareIPs()
    {
        $result = $this->apiCall('post', '');

        return $this->factory($result, ['class' => 'Networking/Ipv4\Share\I\P', 'parameters' => ['id']]);
    }
}
