<?php

namespace HnhDigital\LinodeApi\Networking;

/*
 * This file is part of the PHP Linode API.
 *
 * (c) H&H|Digital <hello@hnh.digital>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use HnhDigital\LinodeApi\Foundation\Base;

/**
 * This is the ipv6 class.
 *
 * This file is automatically generated.
 *
 * @link https://developers.linode.com/v4/reference/endpoints/networking/ipv6
 *
 * @author Rocco Howard <rocco@hnh.digital>
 */
class ipv6 extends Base
{
    /**
     * Endpoint.
     *
     * @var string
     */
    protected $endpoint = 'networking/ipv6';
    /**
     * Constructor.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Returns a list of IPv6 Addresses.
     *
     * @link https://developers.linode.com/v4/reference/endpoints/networking/ipv6#GET
     *
     * @return array
     */
    public function search()
    {
        return $this->apiSearch($this->endpoint);
    }
}
