<?php

namespace HnhDigital\LinodeApi\Instance;

/*
 * This file is part of the PHP Linode API.
 *
 * (c) H&H|Digital <hello@hnh.digital>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use HnhDigital\LinodeApi\Api;

/**
 * This is the Backups class.
 *
 * This file is automatically generated.
 *
 * @link https://developers.linode.com/v4/reference/endpoints/linode/instances/$id/backups
 * @author Rocco Howard <rocco@hnh.digital>
 */
class Backups extends Api
{
    /**
     * Endpoint.
     *
     * @var string
     */
    protected $endpoint = 'linode/instances/%s/backups';

    /**
     * Endpoint placeholders.
     *
     * @var array
     */
    protected $endpoint_placeholders = [];

    /**
     * linode_id.
     *
     * @var integer
     */
    protected $linode_id;

    /**
     * Constructor.
     *
     * @return void
     */
    public function __construct($linode_id, $load = true)
    {
        $this->linode_id = $linode_id;
        $this->endpoint_placeholders = [$linode_id];
    }

    /**
     * Returns a Backups Response with information on this Linode's available backups.
     *
     * @link https://developers.linode.com/v4/reference/endpoints/linode/instances/$id/backups#GET
     *
     * @return array
     */
    public function all()
    {
        return $this->call('get', '');
    }

    /**
     * Creates a snapshot backup of a Linode. WARNING: If you already have a snapshot, this is a destructive operation. The previous snapshot will be deleted.
     *
     * @param string $label (optional) Human-friendly label for this snapshot. Must be 1-50 characters.
     *
     * @link https://developers.linode.com/v4/reference/endpoints/linode/instances/$id/backups#POST
     * 
     * @return bool
     */
    public function create($label = 'null')
    {
        return $this->call('post', "", []);
    }

}
