<?php

namespace HnhDigital\LinodeApi\Instance;

/*
 * This file is part of the PHP Linode API.
 *
 * (c) H&H|Digital <hello@hnh.digital>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use HnhDigital\LinodeApi\Foundation\Base;

/**
 * This is the Config class.
 *
 * This file is automatically generated.
 *
 * @link https://developers.linode.com/v4/reference/endpoints/linode/instances/$id/configs/$id
 *
 * @author Rocco Howard <rocco@hnh.digital>
 */
class Config extends Base
{
    /**
     * Endpoint.
     *
     * @var string
     */
    protected $endpoint = 'linode/instances/%s/configs/%s';
    /**
     * Linode Id.
     *
     * @var int
     */
    protected $linode_id;
    /**
     * Config Id.
     *
     * @var int
     */
    protected $config_id;
    /**
     * Constructor.
     *
     * @return void
     */
    public function __construct($linode_id, $config_id)
    {
        $this->linode_id = $linode_id;
        $this->config_id = $config_id;
        parent::__construct($linode_id, $config_id);
    }

    /**
     * Returns information about this Linode config.
     *
     * @link https://developers.linode.com/v4/reference/endpoints/linode/instances/$id/configs/$id#GET
     *
     * @return array
     */
    public function get()
    {
        return $this->apiCall('get', '');
    }

    /**
     * Modifies a given Linode config.
     *
     * @link https://developers.linode.com/v4/reference/endpoints/linode/instances/$id/configs/$id#PUT
     *
     * @return void
     */
    public function update($optional = [])
    {
        return $this->apiCall('put', '', ['json' => $this->getDirty($optional)]);
    }

    /**
     * Deletes a given Linode config.
     *
     * @link https://developers.linode.com/v4/reference/endpoints/linode/instances/$id/configs/$id#DELETE
     *
     * @return void
     */
    public function delete()
    {
        return $this->apiCall('delete', '');
    }
}
