<?php

namespace HnhDigital\LinodeApi\Instance;

/*
 * This file is part of the PHP Linode API.
 *
 * (c) H&H|Digital <hello@hnh.digital>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use HnhDigital\LinodeApi\Foundation\Base;

/**
 * This is the Disk class.
 *
 * This file is automatically generated.
 *
 * @link https://developers.linode.com/v4/reference/endpoints/linode/instances/$id/disks/$id
 *
 * @author Rocco Howard <rocco@hnh.digital>
 */
class Disk extends Base
{
    /**
     * Endpoint.
     *
     * @var string
     */
    protected $endpoint = 'linode/instances/%s/disks/%s';
    /**
     * Linode Id.
     *
     * @var int
     */
    protected $linode_id;
    /**
     * Disk Id.
     *
     * @var int
     */
    protected $disk_id;
    /**
     * Constructor.
     *
     * @return void
     */
    public function __construct($linode_id, $disk_id)
    {
        $this->linode_id = $linode_id;
        $this->disk_id = $disk_id;
        parent::__construct($linode_id, $disk_id);
    }

    /**
     * Returns information about this disk.
     *
     * @link https://developers.linode.com/v4/reference/endpoints/linode/instances/$id/disks/$id#GET
     *
     * @return array
     */
    public function get()
    {
        return $this->apiCall('get', '');
    }

    /**
     * Updates a disk's metadata.
     *
     * @param array $optional
     *                        - [label] (string) Label of the disk.
     *
     * @link https://developers.linode.com/v4/reference/endpoints/linode/instances/$id/disks/$id#PUT
     *
     * @return void
     */
    public function update($optional = [])
    {
        return $this->apiCall('put', '', ['json' => $this->getDirty($optional)]);
    }

    /**
     * Resets the root password of a disk.
     *
     * @param string $password New root password for the OS installed on this disk.
     *
     * @link https://developers.linode.com/v4/reference/endpoints/linode/instances/$id/disks/$id/password
     *
     * @return bool
     */
    public function password($password)
    {
        return $this->apiCall('post', '/password', ['json' => [
            'password' => $password,
        ]]);
    }

    /**
     * Resizes the disk. The Linode this disk is attached to must be shut down for resizing to take effect.
     *
     * @param int $size The desired size of the disk in MB.
     *
     * @link https://developers.linode.com/v4/reference/endpoints/linode/instances/$id/disks/$id/resize
     *
     * @return bool
     */
    public function resize($size)
    {
        return $this->apiCall('post', '/resize', ['json' => [
            'size' => $size,
        ]]);
    }

    /**
     * Deletes this disk. This action cannot be undone.
     *
     * @link https://developers.linode.com/v4/reference/endpoints/linode/instances/$id/disks/$id#DELETE
     *
     * @return void
     */
    public function delete()
    {
        return $this->apiCall('delete', '');
    }
}
