<?php

namespace HnhDigital\LinodeApi\Instance;

/*
 * This file is part of the PHP Linode API.
 *
 * (c) H&H|Digital <hello@hnh.digital>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use HnhDigital\LinodeApi\Foundation\Base;

/**
 * This is the Ip class.
 *
 * This file is automatically generated.
 *
 * @link https://developers.linode.com/v4/reference/endpoints/linode/instances/$id/ips/$ip_address
 *
 * @author Rocco Howard <rocco@hnh.digital>
 */
class Ip extends Base
{
    /**
     * Endpoint.
     *
     * @var string
     */
    protected $endpoint = 'linode/instances/%s/ips/%s';
    /**
     * Linode Id.
     *
     * @var int
     */
    protected $linode_id;
    /**
     * Ip Address.
     *
     * @var string
     */
    protected $ip_address;
    /**
     * Constructor.
     *
     * @return void
     */
    public function __construct($linode_id, $ip_address)
    {
        $this->linode_id = $linode_id;
        $this->ip_address = $ip_address;
        parent::__construct($linode_id, $ip_address);
    }

    /**
     * Returns information about this IPv4 or IPv6 Address.
     *
     * @link https://developers.linode.com/v4/reference/endpoints/linode/instances/$id/ips/$ip_address#GET
     *
     * @return array
     */
    public function get()
    {
        return $this->apiCall('get', '');
    }

    /**
     * Update this IP Address.
     *
     * @link https://developers.linode.com/v4/reference/endpoints/linode/instances/$id/ips/$ip_address#PUT
     *
     * @return void
     */
    public function update($optional = [])
    {
        return $this->apiCall('put', '', ['json' => $this->getDirty($optional)]);
    }

    /**
     * Delete a public IPv4 address associated with this Linode.
     *
     * @link https://developers.linode.com/v4/reference/endpoints/linode/instances/$id/ips/$ip_address#DELETE
     *
     * @return void
     */
    public function delete()
    {
        return $this->apiCall('delete', '');
    }
}
