<?php

namespace HnhDigital\LinodeApi\Linode\Instances;

/*
 * This file is part of the PHP Linode API.
 *
 * (c) H&H|Digital <hello@hnh.digital>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use HnhDigital\LinodeApi\Foundation\Base;

/**
 * This is the Backup class.
 *
 * This file is automatically generated.
 *
 * @link https://developers.linode.com/api/v4#tag/Linode-Instances-Backups
 *
 * @author Rocco Howard <rocco@hnh.digital>
 */
class Backup extends Base
{
    /**
     * Endpoint.
     *
     * @var string
     */
    protected $endpoint = 'linode/instances/%s/backups/%s';

    /**
     * Linode Id.
     *
     * @var int
     */
    protected $linode_id;

    /**
     * This model is fillable.
     *
     * @var bool
     */
    protected $fillable = true;

    /**
     * This model's method that provides the data to fill it.
     *
     * @var string
     */
    protected $fill_method = 'get';

    /**
     * Constructor.
     *
     * @return void
     */
    public function __construct($linode_id, $fill = [])
    {
        $this->linode_id = $linode_id;
        parent::__construct($linode_id, $fill);
    }

    /**
     * Returns information about a Backup.
     *
     * @link https://developers.linode.com/api/v4#operation/getBackup
     *
     * @return array
     */
    public function get($backup_id)
    {
        return $this->apiCall('get', '', [], ['auto-fill' => true]);
    }

    /**
     * Restores a Linode's Backup to the specified Linode.
     *
     * @param int $linode_id The ID of the Linode that the Backup belongs to.
     * @param int $backup_id The ID of the Backup to restore.
     *
     * @link https://developers.linode.com/api/v4#operation/restoreBackup
     *
     * @return mixed
     */
    public function restoreBackup($backup_id, $optional = [])
    {
        return $this->apiCall('post', '/restore', ['json' => array_merge([
            'linode_id' => $linode_id,
            'backup_id' => $backup_id,
        ], $optional)]);
    }
}
