<?php

namespace HnhDigital\LinodeApi\Account;

/*
 * This file is part of the PHP Linode API.
 *
 * (c) H&H|Digital <hello@hnh.digital>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use HnhDigital\LinodeApi\Foundation\Base;

/**
 * This is the Event class.
 *
 * This file is automatically generated.
 *
 * @link https://developers.linode.com/api/v4#tag/Account-Events
 *
 * @author Rocco Howard <rocco@hnh.digital>
 */
class Event extends Base
{
    /**
     * Endpoint.
     *
     * @var string
     */
    protected $endpoint = 'account/events/%s';
    /**
     * Event Id.
     *
     * @var 
     */
    protected $event_id;

    /**
     * Constructor.
     *
     * @return void
     */
    public function __construct($event_id)
    {
        $this->event_id = $event_id;
        parent::__construct($event_id);
    }

    /**
     * Returns a single Event object.
     *
     * @link https://developers.linode.com/api/v4#operation/getEvent
     *
     * @return array
     */
    public function get()
    {
        return $this->apiCall('get', '');
    }

    /**
     * Marks a single Event as read.
     *
     * @param int $event_id The ID of the Event to designate as read.
     *
     * @link https://developers.linode.com/api/v4#operation/eventRead
     *
     * @return mixed
     */
    public function eventRead()
    {
        return $this->apiCall('post', '/read', ['json' => [
            'event_id' => $event_id,
        ]]);
    }

    /**
     * Marks all Events up to and including this Event by ID as seen.
     *
     * @param int $event_id The ID of the Event to designate as seen.
     *
     * @link https://developers.linode.com/api/v4#operation/eventSeen
     *
     * @return mixed
     */
    public function eventSeen()
    {
        return $this->apiCall('post', '/seen', ['json' => [
            'event_id' => $event_id,
        ]]);
    }
}
