<?php

namespace HnhDigital\LinodeApi\Account;

/*
 * This file is part of the PHP Linode API.
 *
 * (c) H&H|Digital <hello@hnh.digital>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use HnhDigital\LinodeApi\Foundation\Base;

/**
 * This is the Notifications class.
 *
 * This file is automatically generated.
 *
 * @link https://developers.linode.com/api/v4#tag/Account-Notifications
 *
 * @author Rocco Howard <rocco@hnh.digital>
 */
class Notifications extends Base
{
    /**
     * Endpoint.
     *
     * @var string
     */
    protected $endpoint = 'account/notifications';


    /**
     * Constructor.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Returns a collection of Notification objects representing important, often time-sensitive items related to your Account.
     * You cannot interact directly with Notifications, and a Notification will disappear when the circumstances causing it
     * have been resolved. For example, if you have an important Ticket open, you must respond to the Ticket to dismiss the
     * Notification.
     *
     * @link https://developers.linode.com/api/v4#operation/getNotifications
     *
     * @return array
     */
    public function get()
    {
        return $this->apiCall('get', '');
    }
}
